config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :customers

  resources :territories

  resources :regions

  resources :employee_territories

  resources :employees

  resources :shippers

  resources :orders

  resources :suppliers

  resources :order_details

  resources :categories

  resources :products

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :orders
  has_many :employee_territories
end

app/models/employee_territorie.rb
class EmployeeTerritorie < ActiveRecord::Base
  belongs_to :territorie
  belongs_to :employee
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_details
  belongs_to :shipper
  belongs_to :employee
  belongs_to :customer
  has_many :products, :through => :order_details
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :order_details
  belongs_to :supplier
  has_many :orders, :through => :order_details
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :territories
end

app/models/shipper.rb
class Shipper < ActiveRecord::Base
  has_many :orders
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_many :products
end

app/models/territorie.rb
class Territorie < ActiveRecord::Base
  belongs_to :region
  has_many :employee_territories
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:last_name, :first_name, :title, :title_of_courtesy, :birth_date, :hire_date, :address, :city, :region, :postal_code, :country, :home_phone, :extension, :notest, :reports_to, :photo_path)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/order_details_helper.rb
module OrderDetailsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/shippers_helper.rb
module ShippersHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/territories_helper.rb
module TerritoriesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :title_of_courtesy %><br>
    <%= f.text_field :title_of_courtesy %>
  </div>
  <div class="field">
    <%= f.label :birth_date %><br>
    <%= f.datetime_select :birth_date %>
  </div>
  <div class="field">
    <%= f.label :hire_date %><br>
    <%= f.datetime_select :hire_date %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :region %><br>
    <%= f.text_field :region %>
  </div>
  <div class="field">
    <%= f.label :postal_code %><br>
    <%= f.text_field :postal_code %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :home_phone %><br>
    <%= f.text_field :home_phone %>
  </div>
  <div class="field">
    <%= f.label :extension %><br>
    <%= f.text_field :extension %>
  </div>
  <div class="field">
    <%= f.label :notest %><br>
    <%= f.text_area :notest %>
  </div>
  <div class="field">
    <%= f.label :reports_to %><br>
    <%= f.number_field :reports_to %>
  </div>
  <div class="field">
    <%= f.label :photo_path %><br>
    <%= f.text_field :photo_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <thead>
    <tr>
      <th>Last name</th>
      <th>First name</th>
      <th>Title</th>
      <th>Title of courtesy</th>
      <th>Birth date</th>
      <th>Hire date</th>
      <th>Address</th>
      <th>City</th>
      <th>Region</th>
      <th>Postal code</th>
      <th>Country</th>
      <th>Home phone</th>
      <th>Extension</th>
      <th>Notest</th>
      <th>Reports to</th>
      <th>Photo path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.last_name %></td>
        <td><%= employee.first_name %></td>
        <td><%= employee.title %></td>
        <td><%= employee.title_of_courtesy %></td>
        <td><%= employee.birth_date %></td>
        <td><%= employee.hire_date %></td>
        <td><%= employee.address %></td>
        <td><%= employee.city %></td>
        <td><%= employee.region %></td>
        <td><%= employee.postal_code %></td>
        <td><%= employee.country %></td>
        <td><%= employee.home_phone %></td>
        <td><%= employee.extension %></td>
        <td><%= employee.notest %></td>
        <td><%= employee.reports_to %></td>
        <td><%= employee.photo_path %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Last name:</strong>
  <%= @employee.last_name %>
</p>

<p>
  <strong>First name:</strong>
  <%= @employee.first_name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @employee.title %>
</p>

<p>
  <strong>Title of courtesy:</strong>
  <%= @employee.title_of_courtesy %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @employee.birth_date %>
</p>

<p>
  <strong>Hire date:</strong>
  <%= @employee.hire_date %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @employee.city %>
</p>

<p>
  <strong>Region:</strong>
  <%= @employee.region %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @employee.postal_code %>
</p>

<p>
  <strong>Country:</strong>
  <%= @employee.country %>
</p>

<p>
  <strong>Home phone:</strong>
  <%= @employee.home_phone %>
</p>

<p>
  <strong>Extension:</strong>
  <%= @employee.extension %>
</p>

<p>
  <strong>Notest:</strong>
  <%= @employee.notest %>
</p>

<p>
  <strong>Reports to:</strong>
  <%= @employee.reports_to %>
</p>

<p>
  <strong>Photo path:</strong>
  <%= @employee.photo_path %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>