config/routes.rb
Rails.application.routes.draw do
  devise_for :customers
  resources :customers

  resources :territories

  resources :regions

  resources :employee_territories

  resources :employees

  resources :shippers

  resources :orders

  resources :suppliers

  resources :order_details

  resources :categories

  resources :products

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :orders
  has_many :employee_territories
end

app/models/order.rb
class Order < ActiveRecord::Base
  has_many :order_details
  belongs_to :shipper
  belongs_to :employee
  belongs_to :customer
  has_many :products, :through => :order_details
end

app/models/order_detail.rb
class OrderDetail < ActiveRecord::Base
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :order_details
  belongs_to :supplier
  has_many :orders, :through => :order_details
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_many :territories
end

app/models/shipper.rb
class Shipper < ActiveRecord::Base
  has_many :orders
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  has_many :products
end

app/models/territorie.rb
class Territorie < ActiveRecord::Base
  belongs_to :region
  has_many :employee_territories
end

app/controllers/employee_territories_controller.rb
class EmployeeTerritoriesController < ApplicationController
  before_action :set_employee_territory, only: [:show, :edit, :update, :destroy]

  # GET /employee_territories
  # GET /employee_territories.json
  def index
    @employee_territories = EmployeeTerritorie.all
  end

  # GET /employee_territories/1
  # GET /employee_territories/1.json
  def show
  end

  # GET /employee_territories/new
  def new
    @employee_territory = EmployeeTerritorie.new
  end

  # GET /employee_territories/1/edit
  def edit
  end

  # POST /employee_territories
  # POST /employee_territories.json
  def create
    @employee_territory = EmployeeTerritorie.new(employee_territory_params)

    respond_to do |format|
      if @employee_territory.save
        format.html { redirect_to @employee_territory, notice: 'Employee territorie was successfully created.' }
        format.json { render :show, status: :created, location: @employee_territory }
      else
        format.html { render :new }
        format.json { render json: @employee_territory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employee_territories/1
  # PATCH/PUT /employee_territories/1.json
  def update
    respond_to do |format|
      if @employee_territory.update(employee_territory_params)
        format.html { redirect_to @employee_territory, notice: 'Employee territorie was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee_territory }
      else
        format.html { render :edit }
        format.json { render json: @employee_territory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employee_territories/1
  # DELETE /employee_territories/1.json
  def destroy
    @employee_territory.destroy
    respond_to do |format|
      format.html { redirect_to employee_territories_url, notice: 'Employee territorie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee_territory
      @employee_territory = EmployeeTerritorie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_territory_params
      params[:employee_territory]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/employee_territories_helper.rb
module EmployeeTerritoriesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/shippers_helper.rb
module ShippersHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/helpers/territories_helper.rb
module TerritoriesHelper
end

app/views/employee_territories/_form.html.erb
<%= form_for(@employee_territory) do |f| %>
  <% if @employee_territory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee_territory.errors.count, "error") %> prohibited this employee_territory from being saved:</h2>

      <ul>
      <% @employee_territory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employee_territories/edit.html.erb
<h1>Editing employee_territory</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee_territory %> |
<%= link_to 'Back', employee_territories_path %>

app/views/employee_territories/index.html.erb
<h1>Listing employee_territories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employee_territories.each do |employee_territory| %>
      <tr>
        <td><%= link_to 'Show', employee_territory %></td>
        <td><%= link_to 'Edit', edit_employee_territory_path(employee_territory) %></td>
        <td><%= link_to 'Destroy', employee_territory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee territorie', new_employee_territory_path %>

app/views/employee_territories/new.html.erb
<h1>New employee_territory</h1>

<%= render 'form' %>

<%= link_to 'Back', employee_territories_path %>

app/views/employee_territories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_employee_territory_path(@employee_territory) %> |
<%= link_to 'Back', employee_territories_path %>